version: '3.7'
volumes:
  app:
  app_gems:
  postgres:
  solr_data:
services:
  postgres:
    image: "postgres:15.0-alpine"
    container_name: "hxs-blacklight-postgres"
    restart: always
    env_file: .env
    ports:
      - '5438:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  solr:
    image: "solr:9.0.0"
    container_name: "hxs-blacklight-solr"
    env_file: .env
    volumes:
      - ./solr/conf:/opt/solr/conf
      - solr_data:/var/solr
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hxs-blacklight-app"
    env_file: .env
    volumes:
      - .:/app
      - app_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
    command:
      - "bundle"
      - "exec"
      - "rails"
      - "server"
      - "-p"
      - "3000"
      - "-b"
      - "0.0.0.0"
    links:
      - postgres
      - solr
    depends_on:
      - postgres
      - solr
