version: '2'
volumes:
  app:
  mysql:
  redis:
  bundle:
  solr:
  tmp-data:
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: "hxs-blacklight-mysql"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql:delegated
  redis:
    image: redis:4.0-alpine
    container_name: "hxs-blacklight-redis"
    command: redis-server
    volumes:
      - redis:/data
  solr:
    image: "solr:latest"
    container_name: "hxs-blacklight-solr"
    env_file: .env
    volumes:
      - ./solr/conf:/opt/solr/conf
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hxs-blacklight-app"
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command:
      - "bundle"
      - "exec"
      - "rails"
      - "server"
      - "-p"
      - "3000"
      - "-b"
      - "0.0.0.0"
    depends_on:
      - mysql
      - redis
      - solr
